[package]
name = "phimmuno-engine"
version = "1.0.0"
edition = "2024"
license-file = "LICENSE"
readme = "README"

[dependencies]
aho-corasick = "1.1.3"

[profile.release]
lto = true
strip = true
opt-level = 3